services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  postgres:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_PASSWORD: test12345
      POSTGRES_USER: calculator
      POSTGRES_DB: calculator
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calculator"]
      interval: 10s
      timeout: 10s
      retries: 5
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
    env_file:
      - ./frontend/.env
networks:
  default:
    name: expression_calculator_network
